#!/bin/sh

echo 1 > /sys/bus/pci/rescan
pci_dev="$(lspci -n -d 1172: | sed -e 's/\([0-9:]\+\) .*$/\1/')"
if [ -z "$pci_dev" ] ; then
  echo "PCI device not found"
  exit 1
fi
echo "pci_dev=$pci_dev"
pci_dev_dir="$(find /sys/devices/ -name "*$pci_dev" | sed -n -e "s/\(\/sys\/devices\/pci.*\/[0:]*$pci_dev\)/\1/p" )"
if [ -z "$pci_dev_dir" ] ; then
  echo "PCI device directory not found"
  exit 1
fi
echo "pci_dev_dir=$pci_dev_dir"
echo 1 >"$pci_dev_dir"/remove
echo 1 > /sys/bus/pci/rescan
lspci -nn -v -s "$pci_dev"
echo 1 >"$pci_dev_dir"/enable
pci_dev_bar1_addr="$(cat "$pci_dev_dir"/resource | sed -n -s '2s/^\(0x[0-9a-fA-Fx]\+\) .*$/\1/p')"
echo "pci_dev_bar1_addr=$pci_dev_bar1_addr"
if [ -z "$pci_dev_bar1_addr" ] ; then
  echo "PCI device bar 1 address not found"
  exit 1
fi
echo rdwrmem -b 4 -s "$pci_dev_bar1_addr" -l 0x100 -m
rdwrmem -b 4 -s "$pci_dev_bar1_addr" -l 0x100 -m

